from __future__ import annotations

import hashlib
import os
import shutil
import subprocess  # nosec B404 - controlled git metadata queries
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from .pipeline_stats_shared import (
    compute_stats,
    load_status_map,
    now_iso,
    print_summary,
    save_plots,
    write_csv,
    write_json,
)


def _atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            delete=False,
            dir=path.parent,
        ) as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
            tmp_path = Path(fh.name)
        tmp_path.replace(path)
    finally:
        if tmp_path is not None and tmp_path.exists():
            tmp_path.unlink(missing_ok=True)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def default_status_file() -> Path:
    return repo_root() / ".local" / "rdamsc_pipeline_status.json"


def default_pipeline_log_file() -> Path:
    return repo_root() / ".local" / "bootstrap_rdamsc.log"


def default_freeze_dir() -> Path:
    return repo_root() / "exports" / "pipeline" / "latest"


def default_sssom_dir() -> Path:
    return repo_root() / "exports" / "sssom"


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        while True:
            chunk = fh.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def _git_output(root: Path, args: list[str]) -> str:
    try:
        completed = subprocess.run(  # nosec B603,B607 - fixed git subcommands in local repo context
            ["git", *args],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
            timeout=15,
        )
    except Exception:
        return ""
    return completed.stdout.strip()


def git_metadata(root: Path) -> dict[str, object]:
    status_short = _git_output(root, ["status", "--short"])
    return {
        "repo_root": str(root),
        "commit": _git_output(root, ["rev-parse", "HEAD"]),
        "commit_short": _git_output(root, ["rev-parse", "--short", "HEAD"]),
        "commit_date": _git_output(root, ["show", "-s", "--format=%cI", "HEAD"]),
        "branch": _git_output(root, ["rev-parse", "--abbrev-ref", "HEAD"]),
        "remote_origin": _git_output(root, ["remote", "get-url", "origin"]),
        "is_dirty": bool(status_short),
    }


def env_metadata() -> dict[str, object]:
    keys = [
        "KAIGRAPH_USE_SURREAL",
        "KAIGRAPH_DB_URL",
        "KAIGRAPH_DB_NS",
        "KAIGRAPH_DB_NAME",
        "BLABLADOR_BASE_URL",
        "KAIGRAPH_LLM_MODEL",
    ]
    out: dict[str, object] = {key: os.getenv(key, "") for key in keys}
    out["BLABLADOR_API_KEY_loaded"] = bool(os.getenv("BLABLADOR_API_KEY"))
    return out


def write_pipeline_log_snapshot(source_log: Path, target_log: Path) -> str:
    target_log.parent.mkdir(parents=True, exist_ok=True)
    if source_log.exists():
        shutil.copy2(source_log, target_log)
        return "copied"
    note = (
        "No persisted pipeline runtime log was found at freeze time.\n"
        "This snapshot was generated from the pipeline status JSON.\n"
        f"Expected log path: {source_log}\n"
    )
    _atomic_write_text(target_log, note)
    return "placeholder"


def write_sssom_provenance(
    *,
    sssom_dir: Path,
    freeze_dir: Path,
    status_file: Path,
    summary: dict[str, object],
    git_meta: dict[str, object],
    env_meta: dict[str, object],
    command_line: str,
) -> None:
    sssom_dir.mkdir(parents=True, exist_ok=True)
    files = sorted(sssom_dir.glob("*.sssom.tsv"))

    file_rows: list[dict[str, object]] = []
    for path in files:
        stat = path.stat()
        file_rows.append(
            {
                "file": path.name,
                "sha256": _sha256_file(path),
                "size_bytes": stat.st_size,
                "mtime_utc": datetime.fromtimestamp(
                    stat.st_mtime,
                    tz=timezone.utc,
                ).isoformat(),
            }
        )

    manifest = {
        "generated_at": now_iso(),
        "purpose": "Provenance for committed SSSOM files generated by RDAMSC pipeline",
        "command": command_line,
        "status_file": str(status_file.resolve()),
        "freeze_snapshot_dir": str(freeze_dir.resolve()),
        "git": git_meta,
        "environment": env_meta,
        "pipeline_summary": {
            "total_crosswalks": summary.get("total_crosswalks", 0),
            "status_counts": summary.get("status_counts", {}),
            "reason_counts": summary.get("reason_counts", {}),
        },
        "sssom_file_count": len(file_rows),
        "sssom_files": file_rows,
        "note": (
            "Pipeline logic, prompts, model backends, and retrieval strategy can change. "
            "Use git commit metadata and file checksums for reproducibility."
        ),
    }
    write_json(sssom_dir / "generation_manifest.json", manifest)

    md_lines = [
        "# Generated SSSOM provenance",
        "",
        "These SSSOM files were generated from the RDAMSC pipeline and frozen for commit.",
        "",
        f"- Generated at (UTC): `{manifest['generated_at']}`",
        f"- Commit: `{git_meta.get('commit_short')}` ({git_meta.get('branch')})",
        f"- Dirty working tree at freeze time: `{git_meta.get('is_dirty')}`",
        f"- Pipeline status source: `{status_file.resolve()}`",
        f"- Frozen analytics snapshot: `{freeze_dir.resolve()}`",
        f"- SSSOM files included: `{len(file_rows)}`",
        "",
        "## Summary",
        f"- Total crosswalks: `{summary.get('total_crosswalks', 0)}`",
        f"- Status counts: `{summary.get('status_counts', {})}`",
        f"- Failure reasons: `{summary.get('reason_counts', {})}`",
        "",
        "## Reproducibility",
        "- See `generation_manifest.json` in this directory for checksums and metadata.",
        "- See `exports/pipeline/latest/` for status, stats CSV/JSON, and plots.",
        "",
        "## Caveat",
        "- LLM outputs and external artifact availability may vary over time.",
    ]
    _atomic_write_text(
        sssom_dir / "GENERATED_FROM_PIPELINE.md", "\n".join(md_lines) + "\n"
    )


def freeze_outputs(
    *,
    status_file: Path,
    output_dir: Path,
    sssom_dir: Path,
    pipeline_log: Path,
    top_n: int,
    plots: bool,
    print_json: bool,
    command_line: str,
) -> int:
    status_map = load_status_map(status_file)
    stats = compute_stats(status_map, top_n=top_n)
    print_summary(stats.summary, top_n=top_n)

    output_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(status_file, output_dir / "rdamsc_pipeline_status.json")
    write_json(output_dir / "rdamsc_stats_summary.json", stats.summary)
    write_csv(output_dir / "rdamsc_crosswalks.csv", stats.crosswalk_rows)
    write_csv(output_dir / "rdamsc_artifacts.csv", stats.artifact_rows)

    plots_dir = output_dir / "plots"
    if plots:
        if plots_dir.exists():
            shutil.rmtree(plots_dir)
        save_plots(stats.summary, plots_dir, top_n=top_n)

    log_mode = write_pipeline_log_snapshot(pipeline_log, output_dir / "pipeline.log")

    root = repo_root()
    git_meta = git_metadata(root)
    env_meta = env_metadata()

    run_metadata = {
        "generated_at": now_iso(),
        "command": command_line,
        "status_file_used": str(status_file.resolve()),
        "status_file_copied_to": str(
            (output_dir / "rdamsc_pipeline_status.json").resolve()
        ),
        "pipeline_log_source": str(pipeline_log.resolve()),
        "pipeline_log_mode": log_mode,
        "git": git_meta,
        "environment": env_meta,
        "summary": {
            "total_crosswalks": stats.summary.get("total_crosswalks", 0),
            "status_counts": stats.summary.get("status_counts", {}),
            "reason_counts": stats.summary.get("reason_counts", {}),
        },
    }
    write_json(output_dir / "run_metadata.json", run_metadata)

    write_sssom_provenance(
        sssom_dir=sssom_dir,
        freeze_dir=output_dir,
        status_file=status_file,
        summary=stats.summary,
        git_meta=git_meta,
        env_meta=env_meta,
        command_line=command_line,
    )

    if print_json:
        print("\nJSON summary")
        import json

        print(json.dumps(stats.summary, indent=2, ensure_ascii=True))

    print("\nFreeze outputs")
    print(f"  - Snapshot dir: {output_dir}")
    print(f"  - SSSOM provenance: {sssom_dir / 'generation_manifest.json'}")
    print(f"  - SSSOM summary: {sssom_dir / 'GENERATED_FROM_PIPELINE.md'}")
    return 0
